start "npm" /WAIT npm install --save-dev gulp-autoprefixer
start "npm" /WAIT npm install --save-dev gulp-minify-css
start "npm" /WAIT npm install --save-dev gulp-jshint
start "npm" /WAIT npm install --save-dev gulp-jscs
start "npm" /WAIT npm install --save-dev gulp-uglify
start "npm" /WAIT npm install --save-dev gulp-rename
start "npm" /WAIT npm install --save-dev gulp-clean
start "npm" /WAIT npm install --save-dev gulp-concat
start "npm" /WAIT npm install --save-dev gulp-notify
start "npm" /WAIT npm install --save-dev gulp-cache
start "npm" /WAIT npm install --save-dev gulp-util
start "npm" /WAIT npm install --save-dev gulp-print
start "npm" /WAIT npm install --save-dev gulp-if
start "npm" /WAIT npm install --save-dev yargs
start "npm" /WAIT npm install --save-dev gulp-less
start "npm" /WAIT npm install --save-dev gulp-autoprefixer
start "npm" /WAIT npm install --save-dev gulp-plumber
start "npm" /WAIT npm install --save-dev del
start "npm" /WAIT npm install --save-dev gulp-livereload